[WIP] Asset screen implementation
SartiMau/StockAppTandiliOS pull request #10
Opened 2022-01-25 13:28 UTC by ezequielsetzesglobant

The screen that shows a list of assets with their information has been implemented.

Video:
https://user-images.githubusercontent.com/84338513/150985502-58977b8a-6977-4d74-b818-0ec2a38d620b.mov

2022-01-25 13:39 UTC, ezequielsetzesglobant commented
The branch will be closed due to problems with it when doing a rebase. And the link to the new pr will be left.

2022-01-25 13:53 UTC, fn1983 commented on stockApp/stockApp/Data/Entity/Asset.swift
> +        case barcode = "barcode"
```suggestion
        case barcode
```

2022-01-25 13:53 UTC, fn1983 commented on stockApp/stockApp/Data/Entity/Asset.swift
> +        case site = "site"
```suggestion
        case site
```

2022-01-25 13:56 UTC, fn1983 commented on stockApp/stockApp/Data/Entity/Fields.swift
> +    let values: [String] = ["Barcode", "Asset Name", "User Mail", "Location"]
you can have something like this

```
enum FieldsType: String, CaseIterable {
        case barcode = "Barcode" 
        ....
}

let values: [FieldsType] = FieldsType.allCases
```

2022-01-25 21:57 UTC, fn1983 requested changes

2022-01-25 21:57 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/AssetTableViewCell.swift
> +    let barcodeUILabel: UILabel = {
```suggestion
    let barcodeLabel: UILabel = {
```

2022-01-25 21:57 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/AssetTableViewCell.swift
> +    let assetNameUILabel: UILabel = {
```suggestion
    let assetNameLabel: UILabel = {
```

we should add types in variable names.. if you change to another type.. like CUstomLabel. the variable name will contain UILabel .

2022-01-25 21:57 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/AssetTableViewCell.swift
> +    let globerMailUILabel: UILabel = {
```suggestion
    let globerMailLabel: UILabel = {
```

2022-01-25 21:57 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/AssetTableViewCell.swift
> +    let siteUILabel: UILabel = {
```suggestion
    let siteLabel: UILabel = {
```

2022-01-25 21:57 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/AssetTableViewCell.swift
> +    let imageUIImageView: UIImageView = {
```suggestion
    let arrowImageView: UIImageView = {
```
give context to the name!

2022-01-25 21:57 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/AssetView.swift
> +    let searchUIButton: UIButton = {
```suggestion
    let searchButton: UIButton = {
```

change others please!

2022-01-25 21:57 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/AssetView.swift
> +@objc extension AssetView {
```suggestion

@objc extension AssetView {
```

2022-01-25 21:57 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/AssetViewController.swift
> +        viewModel.onNotAssetsFound = {
```suggestion
        viewModel.onNotAssetsFound = { [weak self] in
        guard let self = self else { return }
```

2022-01-25 21:57 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/AssetViewController.swift
> +        viewModel.onThereIsNoInternet = {
```suggestion
        viewModel.onThereIsNoInternet = { [weak self] in
                guard let self = self else { return }
```

2022-01-25 21:57 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/AssetViewController.swift
> +        cell.setFields(assetViewData: assets[indexPath.row])
```suggestion
        let assetViewData = assets[indexPath.row]
        cell.setFields(assetViewData: assetViewData)
```

2022-01-25 21:57 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/MainViewController.swift
> +        // viewModel.showSearchAlert()
```suggestion
```

2022-01-25 21:57 UTC, fn1983 commented on stockApp/stockApp/Presentation/ViewModel/AssetViewModel.swift
> +    internal let useCase: GetAssetUseCaseProtocol
```suggestion
    let useCase: GetAssetUseCaseProtocol
```

if yo don't have frameworks, always it's going to be internal..

2022-01-25 21:57 UTC, fn1983 commented on stockApp/stockApp/Presentation/ViewModel/AssetViewModel.swift
> +    var onThereIsNoInternet: (() -> Void)?
```suggestion
    var onNoInternetConnection: (() -> Void)?
```

check language ..

2022-01-26 13:01 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/View/AssetTableViewCell.swift
> +    let assetNameUILabel: UILabel = {
Do you wanted to put that we shouldn't put a type, right?

2022-01-26 14:27 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/ViewModel/AssetViewModel.swift
> +    var onThereIsNoInternet: (() -> Void)?
done

2022-01-26 14:27 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/ViewModel/AssetViewModel.swift
> +    internal let useCase: GetAssetUseCaseProtocol
done

2022-01-26 14:27 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/View/MainViewController.swift
> +        // viewModel.showSearchAlert()
done

2022-01-26 14:27 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/View/AssetViewController.swift
> +        cell.setFields(assetViewData: assets[indexPath.row])
done

2022-01-26 14:27 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/View/AssetViewController.swift
> +        viewModel.onThereIsNoInternet = {
done

2022-01-26 14:28 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/View/AssetTableViewCell.swift
> +    let imageUIImageView: UIImageView = {
done

2022-01-26 14:28 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/View/AssetTableViewCell.swift
> +    let siteUILabel: UILabel = {
done

2022-01-26 14:28 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/View/AssetTableViewCell.swift
> +    let globerMailUILabel: UILabel = {
done

2022-01-26 14:28 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/View/AssetTableViewCell.swift
> +    let assetNameUILabel: UILabel = {
done

2022-01-26 14:28 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/View/AssetTableViewCell.swift
> +    let barcodeUILabel: UILabel = {
done

2022-01-26 14:28 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Data/Entity/Fields.swift
> +    let values: [String] = ["Barcode", "Asset Name", "User Mail", "Location"]
done

2022-01-26 14:28 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Data/Entity/Asset.swift
> +        case site = "site"
done

2022-01-26 14:28 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Data/Entity/Asset.swift
> +        case barcode = "barcode"
done

2022-01-26 14:58 UTC, fn1983 approved these changes
LGTM .. there are some things to polish but.. so far so good

2022-01-26 15:07 UTC, AgustinaB-Globant approved these changes

2022-01-26 15:20 UTC, merged