Cards information insert into form inputs
SartiMau/StockAppTandiliOS pull request #11
Opened 2022-01-25 18:25 UTC by ignaciocervinoGlob

### Description
Filter information on the cards by the field from the search dialog Link cards to form and charge card information into form inputs, changing the form description to update

#### Tasks:
- [x] Filter information on the cards by the field from the search dialog Link cards to form and charge card information into form inputs
- [x] Change form description when search mode is on Placeholder for message to switch to update mode or cancel
- [x] Unit Test

### Evidence
#### iPhone 11 Pro
![Simulator Screen Recording - iPhone 11 Pro - 2022-01-25 at 15 06 22](https://user-images.githubusercontent.com/90403672/151034017-2dba57a7-e127-49e9-a289-19128ceb2e6d.gif)

### Coverage
#### FormView.setAssetFields
![output-onlinepngtools (38)](https://user-images.githubusercontent.com/90403672/151036456-48af1d72-f86c-4a9c-a9e0-a9ba4073dffb.png)

2022-01-25 22:07 UTC, fn1983 approved these changes
luego reviso cuando tengamos un develop. no deber'iamos hacer rebase de otros branch porque rompe la estructura de arbol de git y no se puede hacer buen code review ya que aparece c'odigo que no esta involucrado en esta tarea

2022-01-25 22:07 UTC, fn1983 commented on stockApp/stockApp/Data/Entity/Fields.swift
> +    let values: [String] = ["Barcode", "Asset Name", "User Mail", "Location"]
you can have a 

```
enum FieldsType: String, CaseIterable {
        case barcode = "Barcode"
        ...
}

let values: [String] = FieldTypes.allCases.map{$0.rawValue} // or better //  let values: [FieldsType] = FieldTypes.allCases

2022-01-26 12:39 UTC, ignaciocervinoGlob commented on stockApp/stockApp/Data/Entity/Fields.swift
> +    let values: [String] = ["Barcode", "Asset Name", "User Mail", "Location"]
done

2022-01-26 12:39 UTC, ignaciocervinoGlob commented on stockApp/stockApp/Data/Entity/Asset.swift
> +    enum CodingKeys: String, CodingKey {
done

2022-01-26 12:39 UTC, ignaciocervinoGlob commented on stockApp/Podfile
> +	pod 'MaterialComponents/Buttons'
done

2022-01-26 12:57 UTC, ignaciocervinoGlob commented on stockApp/Podfile
> +	pod 'MaterialComponents/Buttons'
done

2022-01-26 15:31 UTC, ezequielsetzesglobant approved these changes

2022-01-26 17:52 UTC, fn1983 requested changes

2022-01-26 17:52 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/AssetView.swift
> +<<<<<<< HEAD
won't compile!

2022-01-26 17:52 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/AssetView.swift
> +>>>>>>> 3cb6de5 (using MDCFloatingButton())
same! rebase issu!

2022-01-26 19:37 UTC, ignaciocervinoGlob commented on stockApp/stockApp/Presentation/View/AssetView.swift
> +>>>>>>> 3cb6de5 (using MDCFloatingButton())
done

2022-01-26 19:38 UTC, ignaciocervinoGlob commented on stockApp/stockApp/Presentation/View/AssetView.swift
> +=======
done

2022-01-26 21:06 UTC, fn1983 approved these changes

2022-01-26 21:06 UTC, Faka-GLB approved these changes

2022-01-27 13:16 UTC, AgustinaB-Globant approved these changes

2022-01-27 13:33 UTC, ezequielvelezglobant requested changes

2022-01-27 13:33 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/View/CameraViewController.swift
>  		return view
fix alignment

2022-01-27 13:33 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/View/CameraViewController.swift
> -				HelperFunctions.showAlertMessage(title: Strings.noCameraInput, viewController: self.topMostController() ?? self)
I guess that here are missing code. Error message has to be shown.

2022-01-27 13:33 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/ViewModel/AssetViewModel.swift
> +    }
fix alignment

2022-01-27 14:15 UTC, ignaciocervinoGlob commented on stockApp/stockApp/Presentation/ViewModel/AssetViewModel.swift
> +    }
done

2022-01-27 14:15 UTC, ignaciocervinoGlob commented on stockApp/stockApp/Presentation/View/CameraViewController.swift
> -				HelperFunctions.showAlertMessage(title: Strings.noCameraInput, viewController: self.topMostController() ?? self)
done

2022-01-27 14:15 UTC, ignaciocervinoGlob commented on stockApp/stockApp/Presentation/View/CameraViewController.swift
>  		return view
done

2022-01-27 14:29 UTC, ezequielvelezglobant approved these changes

2022-01-27 14:31 UTC, merged