Improvements from sprint II fixed
SartiMau/StockAppTandiliOS pull request #15
Opened 2022-01-28 19:42 UTC by Faka-GLB

### whats has been done
- [x] Location picker UI: 
Replaced UIPicker with a material components textField, upon clicking it, will display a picker with the locations, when selected a location, picker closes and sets the text.

- [x] Button manually background:
Manual button from the camera screen has its corners unrounded, color changed and moved slightly up

- [x] Hint color gray:
Changed the hints label color to gray, when the user taps on a field the label moves to the top of the field and turns black

-[x] Add icon to save button:
This fix was already solved in the previous sprint

-[x] Add necessary unit tests:
Some unit tests were added/modified with the changes to the form screen

Out of scope fixes:
Unit tests were importing the old app name (with capitalised A) and needed to update some variable names and functions parameters

### Evidence:

Picker and hints colors
| iPhone 8 | iPhone 11 Pro |
|----------|---------------|
| ![Screen Shot 2022-01-28 at 15 13 46](https://user-images.githubusercontent.com/84337198/151609905-8bb21781-bbdc-4483-8be0-776627260ad3.png) | ![Screen Shot 2022-01-28 at 15 13 30](https://user-images.githubusercontent.com/84337198/151609886-f88ac7ba-b6ec-4594-804e-a60a4aa17c67.png) |

Demo:
![demo updated picker](https://user-images.githubusercontent.com/84337198/151610625-bd6b54e9-ff11-4179-8753-3c66d5ba0326.gif)

Manual button background color:
| iPhone 8 | iPhone 11 Pro |
|----------|---------------|
| ![Screen Shot 2022-01-28 at 16 40 47](https://user-images.githubusercontent.com/84337198/151611035-d5026250-35cd-4efa-a3bb-780d7ee80b7e.png) | ![Screen Shot 2022-01-28 at 16 39 40](https://user-images.githubusercontent.com/84337198/151611053-83772383-9656-4225-aa3e-35babb7b7043.png) |

Tests:
![Screen Shot 2022-01-28 at 12 55 06](https://user-images.githubusercontent.com/84337198/151611162-32070e59-006e-4c6a-b57d-ac6d193ef62b.png)

2022-01-28 20:23 UTC, ezequielvelezglobant requested changes

2022-01-28 20:23 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/View/CameraView.swift
> +    static let buttonHeightMultiplier: CGFloat = 0.04
fix alignment

2022-01-28 20:23 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/View/CameraView.swift
>  	}
fix alignment

2022-01-28 20:23 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/View/CameraView.swift
> +                constant: -Constants.buttonBottomSpacing)
fix alignment

2022-01-28 20:23 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/View/FormView.swift
> +    static let locationTextFieldHint = "Location"
fix alignment

2022-01-28 20:23 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/View/FormView.swift
> +        textField.setFloatingLabelColor(Color.tundoraBlack, for: .normal)
fix alignment

2022-01-28 20:23 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/View/FormView.swift
> +        textField.setFloatingLabelColor(Color.tundoraBlack, for: .normal)
fix alignment

2022-01-28 20:23 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/View/FormView.swift
>  		return textField
fix alignment

2022-01-28 20:23 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/View/FormView.swift
> +        locationTextField.inputView = locationPicker
fix alignment

2022-01-28 20:23 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/View/FormView.swift
> +        locationTextField.text = asset.location
fix alignment

2022-01-28 20:23 UTC, ezequielvelezglobant commented on stockApp/stockAppTests/FormViewTest.swift
> +        XCTAssertNotNil(formView.locationTextField)
fix alignment

2022-01-28 20:23 UTC, ezequielvelezglobant commented on stockApp/stockAppTests/FormViewTest.swift
> +        XCTAssertEqual(formView.locationTextField.text, TestConstants.siteTandil)
fix alignment

2022-01-28 20:23 UTC, ezequielvelezglobant commented on stockApp/stockAppTests/FormViewTest.swift
> +            location: TestConstants.siteOther)
fix alignment

2022-01-28 20:25 UTC, ezequielsetzesglobant approved these changes

2022-01-28 20:35 UTC, Faka-GLB commented on stockApp/stockAppTests/FormViewTest.swift
> +            location: TestConstants.siteOther)
done

2022-01-28 20:35 UTC, Faka-GLB commented on stockApp/stockAppTests/FormViewTest.swift
> +        XCTAssertEqual(formView.locationTextField.text, TestConstants.siteTandil)
done

2022-01-28 20:35 UTC, Faka-GLB commented on stockApp/stockAppTests/FormViewTest.swift
> +        XCTAssertNotNil(formView.locationTextField)
done

2022-01-28 20:35 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/FormView.swift
> +        locationTextField.text = asset.location
done

2022-01-28 20:35 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/FormView.swift
> +        locationTextField.inputView = locationPicker
done

2022-01-28 20:35 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/FormView.swift
> +        textField.setFloatingLabelColor(Color.tundoraBlack, for: .normal)
done

2022-01-28 20:35 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/FormView.swift
> +        textField.setFloatingLabelColor(Color.tundoraBlack, for: .normal)
done

2022-01-28 20:35 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/FormView.swift
>  		return textField
done

2022-01-28 20:36 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/FormView.swift
> +    static let locationTextFieldHint = "Location"
done

2022-01-28 20:36 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/CameraView.swift
> +                constant: -Constants.buttonBottomSpacing)
done

2022-01-28 20:36 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/CameraView.swift
>  	}
done

2022-01-28 20:36 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/CameraView.swift
> +    static let buttonHeightMultiplier: CGFloat = 0.04
done

2022-01-31 12:42 UTC, ezequielvelezglobant approved these changes

2022-02-01 13:04 UTC, merged