Bugs solved
SartiMau/StockAppTandiliOS pull request #16
Opened 2022-01-31 14:46 UTC by ezequielsetzesglobant

Two bugs were resolved, the internet check in the form and the filter and value messages in the search dialog of the screen with the list of assets.

Video bug 1:
https://user-images.githubusercontent.com/84338513/151814302-45a1be0c-41e8-4eb4-896b-4c6d3bfbf277.mov

Video bug 2:
https://user-images.githubusercontent.com/84338513/151814464-81e6bd9b-e883-4dc1-8825-a6f1aad27628.mov

2022-01-31 15:18 UTC, ezequielvelezglobant requested changes

2022-01-31 15:18 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/View/FormViewController.swift
> +		self.alertHelper = helper
fix alignment

2022-01-31 15:18 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/View/FormViewController.swift
>  		}
fix alignment

2022-01-31 15:18 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/View/FormViewController.swift
> +            }
catch errors.

2022-01-31 15:18 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/ViewModel/SearchViewModel.swift
> +        static let emptyFilterError = "Please insert a filter"
you "select" a filter

2022-02-01 17:10 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/View/AssetViewController.swift
> +        searchAlertView.delegate = self
done

2022-02-01 17:10 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/View/FormViewController.swift
> +		self.alertHelper = helper
done

2022-02-01 17:11 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/View/FormViewController.swift
>  		}
done

2022-02-01 17:11 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/ViewModel/SearchViewModel.swift
> +        static let emptyFilterError = "Please insert a filter"
done

2022-02-01 17:32 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/View/FormViewController.swift
> +            }
done

2022-02-01 18:12 UTC, ezequielvelezglobant approved these changes

2022-02-01 19:23 UTC, merged