Save asset in Firebase
SartiMau/StockAppTandiliOS pull request #17
Opened 2022-02-01 19:08 UTC by ignaciocervinoGlob

### Description
Saving asset in Firebase:
- FormViewModel calls SaveAssetUseCaseProtocol
- SaveAssetUseCaseProtocol execute the use case and calls the saveAsset in AssetProviderProtocol
- AssetProviderProtocol executes saveAsset service that makes the save in Firebase, it returns success if the asset is saved correctly or failure if something wrong happens

#### Tasks:
- [x] Add internet validation
- [x] In Add asset mode in the form, if all validations are passed, save the information in db
- [x] Create SaveAssetUseCase and its protocol
- [x] Create the service protocol and its implementation
- [ ] Unit tests

### Evidences
#### iPhone 11 Pro

#### No internet case 
https://user-images.githubusercontent.com/90403672/152033135-6ea12aa7-4c15-44a4-bf0c-0f15ecbdce59.mp4

Disclaimer: To test this one I disconnected the Mac from the internet since we can do it in the Xcode emulator

#### Success case
https://user-images.githubusercontent.com/90403672/152033248-4d6cfc9a-c7f4-449a-bdd9-8db2028622cc.mp4

![output-onlinepngtools (45)](https://user-images.githubusercontent.com/90403672/152033325-4cc484d6-4428-44bc-b248-3e917352ae51.png)

2022-02-02 20:12 UTC, ezequielvelezglobant requested changes

2022-02-02 20:12 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/ViewModel/FormViewModel.swift
> +        DispatchQueue.global(qos: .background).async { [self] in
use weak self instead of self

2022-02-02 21:27 UTC, ignaciocervinoGlob commented on stockApp/stockApp/Presentation/ViewModel/FormViewModel.swift
> +        DispatchQueue.global(qos: .background).async { [self] in
done

2022-02-02 21:27 UTC, ignaciocervinoGlob commented on stockApp/stockApp/Presentation/Utility/HelperFunctions.swift
> +                                                     style: .default, handler: {_ in
done

2022-02-02 21:27 UTC, ignaciocervinoGlob commented on stockApp/stockApp/Presentation/Utility/HelperFunctions.swift
> +            alertMessage.addAction(UIAlertAction(title: Strings.okMessage, style: .default, handler: {_ in
done

2022-02-03 12:33 UTC, AgustinaB-Globant approved these changes

2022-02-03 16:57 UTC, ezequielsetzesglobant approved these changes

2022-02-03 20:01 UTC, ezequielvelezglobant approved these changes

2022-02-03 20:06 UTC, merged