Implementation of the search assets in firebase
SartiMau/StockAppTandiliOS pull request #18
Opened 2022-02-04 16:52 UTC by ezequielsetzesglobant

The feature of bringing assets from Firebase with the filter functionality was implemented as well.
In addition, internet validations were made.

Videos case filter by barcode and case all:

Videos case internet validation en camera screen and assets list screen:

Unit test passed:
![Unit test passed 1](https://user-images.githubusercontent.com/84338513/152569391-ccd3e5b7-88dc-40ea-9699-4244479a6bce.png)
![Unit test passed 2](https://user-images.githubusercontent.com/84338513/152569471-a5312c39-8db5-475d-9a5a-1e7f1d3c8277.png)

Coverage:
![Coverage](https://user-images.githubusercontent.com/84338513/152569551-c663f256-94ba-4b32-b52c-b1ee929f33f7.png)

2022-02-04 20:28 UTC, ezequielvelezglobant requested changes

2022-02-04 20:28 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/View/AssetViewController.swift
>  	let searchAlertView = SearchAlertView()
fix alignment of all document

2022-02-04 20:28 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/View/CameraViewController.swift
> +        self.reachability?.stopNotifier()
fix alignment

2022-02-04 20:28 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/View/CameraViewController.swift
> +        alertHelper.showAlertMessage(title: "Error", message: error, viewController: self, handler: {_ in })
fix alignment

2022-02-04 20:28 UTC, ezequielvelezglobant commented on stockApp/stockAppTests/AssetViewModelTest.swift
> +	var displayRequestErrorMessageValue: Bool = false
fix alignment.
review that maybe you have a diferent alignment configuration

2022-02-07 14:46 UTC, ezequielsetzesglobant commented on stockApp/stockAppTests/AssetViewModelTest.swift
> +	var displayRequestErrorMessageValue: Bool = false
done

2022-02-07 14:46 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/View/CameraViewController.swift
> +        alertHelper.showAlertMessage(title: "Error", message: error, viewController: self, handler: {_ in })
done

2022-02-07 14:46 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/View/CameraViewController.swift
> +        self.reachability?.stopNotifier()
done

2022-02-07 14:46 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Presentation/View/AssetViewController.swift
>  	let searchAlertView = SearchAlertView()
done

2022-02-07 14:46 UTC, ezequielsetzesglobant commented on stockApp/stockApp/Domain/UseCase/GetAssetUseCase.swift
> +    }
done

2022-02-07 14:55 UTC, Faka-GLB approved these changes

2022-02-07 15:16 UTC, ezequielvelezglobant approved these changes

2022-02-07 16:41 UTC, merged