[WIP] Created app flow with service
SartiMau/StockAppTandiliOS pull request #22
Opened 2022-02-08 21:28 UTC by Faka-GLB

PR in progress

2022-02-09 19:17 UTC, AgustinaB-Globant approved these changes

2022-02-09 19:55 UTC, ezequielsetzesglobant approved these changes

2022-02-09 20:06 UTC, ezequielvelezglobant requested changes

2022-02-09 20:08 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/Utility/Constants.swift
> +    static let confirmationAlertAddMessage = "This asset does not exists in our database. Do you want to add it??"
They're different strings for different flows in the camera screen

2022-02-09 20:23 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/Utility/Constants.swift
> +    static let confirmationAlertAddMessage = "This asset does not exists in our database. Do you want to add it??"
I mean "Do you want to add it??" "?" from the string

2022-02-09 20:53 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/Protocol/AlertCallbackReceiver.swift
> +}
removed

2022-02-09 20:53 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/CameraViewController.swift
> +                                }))
used [unowned self] instead, because that method cannot execute without the view controller.

2022-02-09 20:53 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/CameraViewController.swift
> +        }
fixed

2022-02-09 20:54 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/Utility/Constants.swift
> +        "This asset has already been saved in our database. Do you want to update the information?"
changed

2022-02-09 20:54 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/Coordinator/AppCoordinator.swift
> +        self.provider = provider
done

2022-02-09 20:56 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/CameraViewController.swift
> +                                }))
the closure capture is for a UIAclertAction, it comes from the AlertHelper function

2022-02-10 12:42 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/Utility/Constants.swift
> +    static let confirmationAlertAddMessage = "This asset does not exists in our database. Do you want to add it??"
oooooooohh i see

2022-02-10 12:51 UTC, ezequielvelezglobant approved these changes

2022-02-10 14:23 UTC, merged