Implemented SearchViewController
SartiMau/StockAppTandiliOS pull request #24
Opened 2022-02-15 15:25 UTC by Faka-GLB

### Whats has been done?

- [x] SearchViewController
- [x] Move alert to vc
- [x] Move data arrays to viewmodel
- [x] Transition from camara/Asset to Search vc
- [x] Unit test

Created SearchViewController and refactored SearchAlertView to just a view Class like the others views.
SearchViewController is used as a child ViewController in the screens that use it, and responds the inputs using the SearchDelegate protocol, wich is implemented in the Camera and Assets ViewControllers.

### Test results and coverage
| Tests results | SearchViewModel Coverage |
|--------------|----------|
| ![Screen Shot 2022-02-15 at 11 53 04](https://user-images.githubusercontent.com/84337198/154092796-3077e799-12f3-46c9-8d83-5cd967ba97c5.png) | ![Screen Shot 2022-02-15 at 11 51 33](https://user-images.githubusercontent.com/84337198/154093033-678bb625-4a87-4162-b3f0-da6ecd668c82.png) |

2022-02-15 19:47 UTC, ezequielsetzesglobant approved these changes

2022-02-15 20:46 UTC, ezequielvelezglobant requested changes

2022-02-15 20:46 UTC, ezequielvelezglobant commented on stockApp/stockApp/Presentation/ViewModel/SearchViewModel.swift
> +            FilterType.all.rawValue]
to avoid that you can have 2 posible solutions:
Solution 1: Make `FilterType` implement `CaseIterable` and `CustomStringConvertible` protocols
Something like this
<img width="898" alt="image" src="https://user-images.githubusercontent.com/84336500/154143629-b38c5e6b-68da-432e-ae4e-fd06e3e96eef.png">
The only problem with that is that you have to replace all `.rawValue` for `.description` 

Solution 2: Make `FilterType` implement `CaseIterable` protocol and define a computed property to return all filters
<img width="927" alt="image" src="https://user-images.githubusercontent.com/84336500/154145739-b625d264-c7b8-4407-9d3c-b8280f237804.png">

2022-02-15 20:46 UTC, ezequielvelezglobant commented on stockApp/stockAppTests/SaveAssetUseCaseTest.swift
> +    }*/
why comment test?

2022-02-15 20:52 UTC, Faka-GLB commented on stockApp/stockAppTests/SaveAssetUseCaseTest.swift
> +    }*/
that test is nade by nacho and it does not run in my version of xcode

2022-02-16 12:23 UTC, ezequielvelezglobant commented on stockApp/stockAppTests/SaveAssetUseCaseTest.swift
> +    }*/
Well but talk with him, the test has to be fixed or removed.

2022-02-16 12:56 UTC, Faka-GLB commented on stockApp/stockAppTests/SaveAssetUseCaseTest.swift
> +    }*/
ezequiel setze modified this test in his barnch

2022-02-16 13:43 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/ViewModel/SearchViewModel.swift
> +            FilterType.all.rawValue]
I liked the second option

2022-02-16 13:49 UTC, ezequielvelezglobant approved these changes

2022-02-16 14:06 UTC, merged