Implemented search custom alert
SartiMau/StockAppTandiliOS pull request #6
Opened 2022-01-19 19:42 UTC by Faka-GLB

- [x] Implemented dynamic button text in the CameraView to show "Add manually" or "Search manually" by using a boolean value in CameraViewController
- [x] Created a SearchCustomAlert class wich can be used by any ViewController to display the alert, the cancel button returns the user to the camera screen and the search buttons perform the same field checks of the form screen and if is valid resume app flow.
- [x] Implemented app flow (for now a valid search returns to the main screen and shows a message with the selected search)
- [x] Implemented unit tests for SearchAlertView and SearchViewModel

Custom alert:
| iPhone 11 pro | iPhone 8 |
|--------------|----------|
| ![Screen Shot 2022-01-26 at 14 02 42](https://user-images.githubusercontent.com/84337198/151211050-3963d785-4ac4-49ea-9929-e29367e37473.png) | ![Screen Shot 2022-01-26 at 14 06 14](https://user-images.githubusercontent.com/84337198/151211630-061d897c-bcbb-41e4-bb67-a24319553716.png) |

Confirmation message:
![Screen Shot 2022-01-19 at 17 08 48](https://user-images.githubusercontent.com/84337198/150206036-be77ad4e-a7bf-46e9-a30b-173a540cd6dd.png)

SearchViewModel test coverage:
![Screen Shot 2022-01-19 at 14 58 48](https://user-images.githubusercontent.com/84337198/150206148-39175ff8-1200-425c-ac94-611c283a435b.png)

Demos:
| feature demo | Verification demo |
|--------------|-------------------|
| ![demo search](https://user-images.githubusercontent.com/84337198/150869254-d532aa4c-32f2-4139-822d-b308c8b763fd.gif) | ![demo 2 search](https://user-images.githubusercontent.com/84337198/150869761-eb689bb3-e520-4312-a14e-5ecfc4b2a4a6.gif) |

2022-01-19 21:10 UTC, fernando-nicola-globant commented on stockApp/stockApp/View/MainViewController.swift
> +        coordinator?.goToCameraViewController(false)
align code

2022-01-20 18:44 UTC, Faka-GLB commented on stockApp/stockApp/View/MainViewController.swift
> +        coordinator?.goToCameraViewController(false)
- [x] done

2022-01-20 20:22 UTC, pablocalcagnino requested changes

2022-01-20 20:22 UTC, pablocalcagnino commented on stockApp/stockApp/Coordinator/AppCoordinator.swift
> +        cameraViewController.isForAddAsset = isForAddAsset
Fix alignment. You can run `switflint fix`.
Also you can add the script as shown in the documentation to fix every time the project is built (https://github.com/realm/SwiftLint)

2022-01-20 20:22 UTC, pablocalcagnino commented on stockApp/stockApp/Coordinator/AppCoordinator.swift
> +            HelperFunctions.showAlertMessage(title: Strings.fieldsSavedCorrectlyMessage,
fix alignment

2022-01-20 20:22 UTC, pablocalcagnino commented on stockApp/stockApp/Coordinator/AppCoordinator.swift
> +            HelperFunctions.showAlertMessage(title: Strings.fieldsSavedCorrectlyMessage,
this could is very difficult to unit test. You can avoid the static func and provide/inject a lazy variable to the coordinator

2022-01-20 20:22 UTC, pablocalcagnino commented on stockApp/stockApp/Coordinator/AppCoordinator.swift
> +        if let firstViewControllerUnwrapped = rootViewController.viewControllers.first {
use a guard instead and avoid nesting the regualr executing of the flow

2022-01-20 20:22 UTC, pablocalcagnino commented on stockApp/stockApp/Utility/HelperFunctions.swift
>  		DispatchQueue.main.async {
why are you returning to the main queue? it is not a responsibility from this class to ensure to be running in the main loop

2022-01-20 20:22 UTC, pablocalcagnino commented on stockApp/stockApp/Coordinator/AppCoordinator.swift
> +    func goToCameraViewController(_ isForAddAsset: Bool) {
I imagine that isForAddAsset is only necessary for one particular flow. You can provide a default value (false) and avoid passing it everywhere

2022-01-20 20:22 UTC, pablocalcagnino commented on stockApp/stockApp/Coordinator/AppCoordinator.swift
> +        cameraViewController.isForAddAsset = isForAddAsset
same here, you can move isForAddAsset to a custom initializer with a default value

2022-01-20 23:56 UTC, fn1983 commented on stockApp/stockApp/Protocols/CameraViewModelProtocol.swift
> +protocol CameraViewModelProtocolInput {
💯

2022-01-21 00:04 UTC, fn1983 requested changes

2022-01-21 00:04 UTC, fn1983 commented on stockApp/stockApp/Protocols/FormViewModelProtocol.swift
>      func checkAutomaticBarcode(view: FormView)
FormView is a UIView which's UIKit.. 
**ViewMODELS** must **NOT** import stuff related to it.. otherwise as soon as you change to swiftUI or something else you'll have to change VM implementation too ..

2022-01-21 00:06 UTC, fn1983 commented on stockApp/stockApp/View/CameraView.swift
> +    let isForAddAsset: Bool
looks like someone has tapstop at 8.. align code please

2022-01-21 00:15 UTC, fn1983 commented on stockApp/stockApp/View/CameraViewController.swift
> +        self.dismiss(animated: true, completion: {
```suggestion
        dismiss(animated: true, completion: {
```

2022-01-21 00:15 UTC, fn1983 commented on stockApp/stockApp/View/CameraViewController.swift
> +        self.searchAlertView.dismissAlert()
```suggestion
        searchAlertView.dismissAlert()
```
only needed if you want to give context

2022-01-21 00:16 UTC, fn1983 commented on stockApp/stockApp/View/CameraViewController.swift
> +        self.searchAlertView.processSearch()
```suggestion
    searchAlertView.processSearch()
```

2022-01-21 00:22 UTC, fn1983 requested changes

2022-01-21 00:22 UTC, fn1983 commented on stockApp/stockApp/View/SearchAlertView.swift
> +        addActions()
duplicated addAction?

2022-01-21 00:22 UTC, fn1983 commented on stockApp/stockApp/View/SearchAlertView.swift
> +            self.validSearch()
check retain cycle with Instruments or check if your viewcontroller is calling `deinit` .. looks like you have a leak here

2022-01-21 00:22 UTC, fn1983 commented on stockApp/stockApp/View/SearchAlertView.swift
> +            self.showError(errorMesage)
also leak

2022-01-21 00:22 UTC, fn1983 commented on stockApp/stockApp/ViewModel/SearchViewModel.swift
> +        if filter == "User mail" {
don't you have a constant for "User mail" ? i'd use a Enum like 

```
enum FilterType: String {
      case userEmail = "User mail"
}
```
and then 

```
if case .userEmail =   FilterType(rawValue: filter) { 
 ....
}
```


this is the way of using type inference in a strong typed language

2022-01-21 20:27 UTC, Faka-GLB commented on stockApp/stockApp/Coordinator/AppCoordinator.swift
> +        cameraViewController.isForAddAsset = isForAddAsset
done

2022-01-21 20:27 UTC, Faka-GLB commented on stockApp/stockApp/Coordinator/AppCoordinator.swift
>          formViewController.viewModel.barcode = barcode
done

2022-01-21 20:27 UTC, Faka-GLB commented on stockApp/stockApp/Coordinator/AppCoordinator.swift
> +            HelperFunctions.showAlertMessage(title: Strings.fieldsSavedCorrectlyMessage,
done

2022-01-21 20:27 UTC, Faka-GLB commented on stockApp/stockApp/Coordinator/AppCoordinator.swift
> +        if let firstViewControllerUnwrapped = rootViewController.viewControllers.first {
done

2022-01-21 20:27 UTC, Faka-GLB commented on stockApp/stockApp/Coordinator/AppCoordinator.swift
> +    func goToCameraViewController(_ isForAddAsset: Bool) {
done

2022-01-21 20:27 UTC, Faka-GLB commented on stockApp/stockApp/Coordinator/AppCoordinator.swift
> +        cameraViewController.isForAddAsset = isForAddAsset
done

2022-01-21 20:28 UTC, Faka-GLB commented on stockApp/stockApp/Protocols/FormViewModelProtocol.swift
>      func checkAutomaticBarcode(view: FormView)
removed UI imports in viewmodels

2022-01-21 20:28 UTC, Faka-GLB commented on stockApp/stockApp/View/CameraViewController.swift
> +        self.searchAlertView.processSearch()
self removed

2022-01-21 20:28 UTC, Faka-GLB commented on stockApp/stockApp/View/SearchAlertView.swift
> +        addActions()
wops, removed an addActions()

2022-01-21 20:31 UTC, Faka-GLB commented on stockApp/stockApp/View/SearchAlertView.swift
> +            self.validSearch()
Intruments didn't show any garbage, still that param wasn't supossed to be there anymore

2022-01-21 20:31 UTC, Faka-GLB commented on stockApp/stockApp/ViewModel/SearchViewModel.swift
> +        if filter == "User mail" {
done

2022-01-21 20:32 UTC, Faka-GLB commented on stockApp/stockApp/Utility/HelperFunctions.swift
>  		DispatchQueue.main.async {
removed DispatchQueue

2022-01-21 20:33 UTC, Faka-GLB commented on stockApp/stockApp/View/SearchAlertView.swift
> +            self.showError(errorMesage)
same as above

2022-01-24 12:59 UTC, fn1983 approved these changes

2022-01-24 13:42 UTC, ignaciocervinoGlob approved these changes

2022-01-24 13:42 UTC, Georgina-Fernandez approved these changes

2022-01-24 14:16 UTC, ezequielsetzesglobant approved these changes

2022-01-24 16:53 UTC, fn1983 commented on stockApp/stockApp/Presentation/Utility/Constants.swift
> +    static let manualInputButtonTextSearchAsset = "Search asset manually"
align

2022-01-24 17:20 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/Utility/Constants.swift
> +    static let manualInputButtonTextSearchAsset = "Search asset manually"
aligned

2022-01-24 17:49 UTC, fn1983 requested changes

2022-01-24 17:49 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/SearchAlertView.swift
> +            self.showError(errorMesage)
add `[weak self]` 

for learning ... add `deinit { print("SearchAlertView deallod") }` 

if it's called then you don't have memory leak. if it's NOT called, then you have a memory leak what you have to fix by using capture list  like `[weak self]`

2022-01-25 13:25 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/CameraViewController.swift
> +        return Ints.numberOfComponents
the value numberOfComponents is also used in another picker in the app, so we decided to move the value from the class to a general constants file

2022-01-25 13:30 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/SearchAlertView.swift
> +            self.showError(errorMesage)
done

2022-01-25 13:52 UTC, fn1983 requested changes
Fix comments and then it's done from my side! good job dude!

2022-01-25 13:52 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/SearchAlertView.swift
> +    deinit {
remove this

2022-01-25 13:52 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/SearchAlertView.swift
> +    let cancelUIbutton: UIButton = {
```suggestion
    let cancelButton: UIButton = {
```

2022-01-25 13:52 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/SearchAlertView.swift
> +    let searchUIbutton: UIButton = {
```suggestion
    let searchButton: UIButton = {
```

2022-01-25 13:52 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/SearchAlertView.swift
> +    let valueUITextField: MDCFilledTextField = {
```suggestion
    let valueTextField: MDCFilledTextField = {
```

this is an example why you don't have to add Types in variableNames..

2022-01-25 13:52 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/SearchAlertView.swift
> +    let filterUITextField: UITextField = {
```suggestion
    let filterTextField: UITextField = {
```

2022-01-25 13:52 UTC, fn1983 commented on stockApp/stockApp/Presentation/View/SearchAlertView.swift
> +    let titleUILabel: UILabel = {
```suggestion
    let titleLabel: UILabel = {
```

2022-01-25 15:53 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/SearchAlertView.swift
> +    deinit {
done

2022-01-25 15:53 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/SearchAlertView.swift
> +    let searchUIbutton: UIButton = {
done

2022-01-25 15:55 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/SearchAlertView.swift
> +    let valueUITextField: MDCFilledTextField = {
done

2022-01-25 21:46 UTC, fn1983 approved these changes

2022-01-26 16:02 UTC, pablocalcagnino requested changes

2022-01-26 16:02 UTC, pablocalcagnino commented on stockApp/stockApp/Presentation/View/CameraViewController.swift
> +        self.dismiss(animated: true, completion: {
avoid using self, use it only in closures and for disambiguation

2022-01-26 16:55 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/CameraViewController.swift
> +        self.dismiss(animated: true, completion: {
self removed

2022-01-26 16:55 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/CameraViewController.swift
> +        if isForAddAsset ?? false {
nullability removed

2022-01-26 16:55 UTC, Faka-GLB commented on stockApp/stockApp/Presentation/View/CameraViewController.swift
> +		viewModel.scanSuccess = { [weak self] barcode in
replaced weak for unowned, guard let removed

2022-01-26 17:03 UTC, pablocalcagnino approved these changes

2022-01-26 17:22 UTC, merged