[WIP] Implementation of the screen of assets
SartiMau/StockAppTandiliOS pull request #7
Opened 2022-01-19 21:16 UTC by ezequielsetzesglobant

The implementation of the assets screen was developed, with a TableView, a button and a description.

Video:
https://user-images.githubusercontent.com/84338513/150215005-c871884f-c132-4818-92ba-68da5a3f34f9.mov

2022-01-19 21:41 UTC, fn1983 commented on stockApp/stockApp/ViewModel/AssetViewModel.swift
> +    var useCase: GetAssetUseCase
```suggestion
    private let useCase: GetAssetUseCase
```

2022-01-19 21:44 UTC, fn1983 commented on stockApp/stockApp/ViewModel/AssetViewModel.swift
> +            onCompletion()
it-s not needed  since we're in mvvm and you have the `observerData` which i'd give a proper and self descriptive name like - onFetchAssets - or something :) 
```suggestion
```

2022-01-19 21:44 UTC, fn1983 commented on stockApp/stockApp/ViewModel/AssetViewModel.swift
> +                self.observerData?(asset)
since you have a Domain layer, what about creating a Data layer ?

2022-01-20 13:45 UTC, ezequielsetzesglobant commented on stockApp/stockApp/ViewModel/AssetViewModel.swift
> +                self.observerData?(asset)
How would that data be, because we don't have a domain folder?

2022-01-20 13:51 UTC, ezequielsetzesglobant commented on stockApp/stockApp/ViewModel/AssetViewModel.swift
> +            onCompletion()
I had done it to be able to test this method, but yes, I am going to remove it

2022-01-20 15:37 UTC, ezequielsetzesglobant commented on stockApp/stockApp/ViewModel/AssetViewModel.swift
> +    var useCase: GetAssetUseCase
If I put private, it say that Property 'useCase' must be declared internal because it matches a requirement in internal protocol 'AssetViewModelProtocol'
let, yes it left me because I deleted the set in the protocol

2022-01-20 19:50 UTC, fn1983 commented on stockApp/stockApp/Model/Asset.swift
> +struct  Asset {
```suggestion
struct Asset {
```

2022-01-20 19:57 UTC, fn1983 commented on stockApp/stockApp/View/AssetTableViewCell.swift
> +    func setFields(barcode: String, assetName: String, globerMail: String, site: String) {
```suggestion
    struct AssetTableViewData(
    func setFields(viewData:  AssetTableViewData) { }
```

2022-01-20 20:05 UTC, fn1983 commented on stockApp/stockApp/View/AssetViewController.swift
> +        viewModel.observerData = { assets in
```suggestion
        viewModel.observerData = { [weak self] assets in
        guard let self = self else { return }
```

2022-01-20 20:05 UTC, fn1983 commented on stockApp/stockApp/View/AssetViewController.swift
> +
deinit {
  printf("AQUI LLEGO")
}

2022-01-21 00:39 UTC, fn1983 requested changes

2022-01-21 00:39 UTC, fn1983 commented on stockApp/stockApp/Model/Response.swift
> +    let assets: [Asset] = [Asset(barcode: "1234", assetName: "notebook", globerMail: "user@globant.com", recordDateTime: "18/01/2022 15:49", site: "Tandil"), Asset(barcode: "1235", assetName: "notebo
hard to tell what are you trying to do here!

2022-01-21 00:39 UTC, fn1983 commented on stockApp/stockApp/Model/Util.swift
> +    let fields: String = "Barcode, Asset Name, User Mail, Location"
sane here!

2022-01-21 00:39 UTC, fn1983 commented on stockApp/stockApp/Protocols/AssetViewModelProtocol.swift
> +    func retrieveData(filter: String, value: String, onCompletion: @escaping () -> Void)
```suggestion
    func retrieveData(filter: String, value: String)
```
give a proper name to the function. like `getAssets(for filter: String, value: String)` 

you variable and functions and class etc must be self-descritive

2022-01-21 00:39 UTC, fn1983 commented on stockApp/stockApp/Protocols/GetAssetUseCaseProtocol.swift
> +    var manager: AssetManager { get set }
don't expose it .. keep it hidden fro the vm ..

2022-01-21 00:39 UTC, fn1983 commented on stockApp/stockApp/UseCase/GetAssetUseCase.swift
> +    var manager: AssetManager
```suggestion
    private let manager: AssetManager
```

2022-01-21 00:39 UTC, fn1983 commented on stockApp/stockApp/UseCase/GetAssetUseCase.swift
> +    init(manager: AssetManager) {
```suggestion
    init(manager: AssetManagerProtocol) {
```

you should use a protocol instead of a concreat class

2022-01-21 00:39 UTC, fn1983 commented on stockApp/stockApp/Utility/Constants.swift
> +    static let searchAssetSearchTitle = "Asset List:"
create an extension 
```swift

extension String {
     var localized: String { 
         NSLocalizationString(self, self)
     }
}

```

2022-01-21 00:39 UTC, fn1983 commented on stockApp/stockApp/Utility/HelperFunctions.swift
> +            alertMessage.addAction(UIAlertAction(title: Strings.cancelMessage, style: .default, handler: nil))
```suggestion
            alertMessage.addAction(UIAlertAction(title: Strings.cancelMessage.localized, style: .default, handler: nil))
```

and then use your previous string extension

2022-01-21 00:39 UTC, fn1983 commented on stockApp/stockApp/View/AssetView.swift
> +        self.addSubview(searchUIButton)
```
        addSubview(searchUIButton)
        addSubview(titleUILabel)
        ddSubview(assetsListUITableView)
```

2022-01-21 00:39 UTC, fn1983 commented on stockApp/stockApp/View/AssetViewController.swift
> +        return AssetViewModel(useCase: GetAssetUseCase(manager: AssetManager()))
try to use `if time` DI tool like

`https://github.com/hmlongco/Resolver` or this one from coworker from globant -> https://github.com/alexruperez/SecurePropertyStorage/

2022-01-21 00:39 UTC, fn1983 commented on stockApp/stockApp/View/AssetViewController.swift
> +        viewModel.retrieveData(filter: "", value: "", onCompletion: {})
```suggestion
        viewModel.retrieveData(filter: "", value: "")
``

2022-01-21 00:39 UTC, fn1983 commented on stockApp/stockApp/View/AssetViewController.swift
> +        cell.setFields(barcode: assets[indexPath.row].barcode, assetName: assets[indexPath.row].assetName, globerMail: assets[indexPath.row].globerMail, site: assets[indexPath.row].site)
Dont repeat yourself


```suggestion
        let model = assets[indexPath.row]
        cell.setFields(barcode: model.barcode, 
                               assetName: model.assetName, 
                               globerMail: model.globerMail, 
                               site: model.site)
```

2022-01-21 00:39 UTC, fn1983 commented on stockApp/stockApp/View/AssetViewController.swift
> +    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
```suggestion
```

don't add nested code

2022-01-21 00:39 UTC, fn1983 commented on stockApp/stockApp/ViewModel/AssetViewModel.swift
> +    var useCase: GetAssetUseCase
it's internal because you don't work with modules..  keep it like that..

2022-01-21 00:39 UTC, fn1983 commented on stockApp/stockApp/ViewModel/AssetViewModel.swift
> +                self.observerData?(asset)
something like this

```
Onion Architecture!
/// DATA
Data/Entities/Modelo1.swift {
    struct Modelo: Decodable {
    	let date: String
    }
	
	func toDomain() -> AssetModel {
    	.init(date: DateFormatter(string: self.date))
	}
	
	private func DateFormatter(string: String) -> Date? {
	}
}
Data/Providers/FetchListOfAssets.swift {
import Domain
final class FetchListOfAssets: FetchListOfAssetsProviderProtocol {
injectServicio(API.swift)
    func f() {
	
	}
}
Service/API.swift {
      llamadaalSericio
}
/// DOMAIN
Domain/Models/AssetModel.swift {
let date: Date
}
Protocol/FetchListOfAssetsProviderProtocol.swift {
    func f()
}
    UseCase/GetAssetsUseCaseProtocol {
         func execute()
    }
UseCase/GetAssetsUseCase.swift {
    let provider: FetchListOfAssetsProviderProtocol
        init(with provider: FetchListOfAssetsProviderProtocol) {
        self.provider = provider
    }
    func execute() {
        provider.f()
    }
}
/// PRESENTATION
var onSuccess: ((...) -> Void)?
ViewModel(useCase: GetAssetsUseCaseProtocol) {
self.useCase = usecase
}
    usecase.execute() {
          onSuccess?(MapperDomain(modelo: ...))
    }
MapperDomain(modelo: DomainModel) -> ViewData {
}
// COORDINATOOnion Architecture!
/// DATA
Data/Entities/Modelo1.swift {
    struct Modelo: Decodable {
    	let date: String
    }
	
	func toDomain() -> AssetModel {
    	.init(date: DateFormatter(string: self.date))
	}
	
	private func DateFormatter(string: String) -> Date? {
	}
}
Data/Providers/FetchListOfAssets.swift {
import Domain
final class FetchListOfAssets: FetchListOfAssetsProviderProtocol {
injectServicio(API.swift)
    func f() {
	
	}
}
Service/API.swift {
      llamadaalSericio
}
/// DOMAIN
Domain/Models/AssetModel.swift {
let date: Date
}
Protocol/FetchListOfAssetsProviderProtocol.swift {
    func f()
}
    UseCase/GetAssetsUseCaseProtocol {
         func execute()
    }
UseCase/GetAssetsUseCase.swift {
    let provider: FetchListOfAssetsProviderProtocol
        init(with provider: FetchListOfAssetsProviderProtocol) {
        self.provider = provider
    }
    func execute() {
        provider.f()
    }
}
/// PRESENTATION
var onSuccess: ((...) -> Void)?
ViewModel(useCase: GetAssetsUseCaseProtocol) {
self.useCase = usecase
}
    usecase.execute() {
          onSuccess?(MapperDomain(modelo: ...))
    }
MapperDomain(modelo: DomainModel) -> ViewData {
}
// COORDINATORR
```

2022-01-25 13:32 UTC, closed without merging

2022-01-25 13:41 UTC, ezequielsetzesglobant commented
The branch will be closed due to problems with it when doing a rebase. And the link to the new pr will be left.